---
#######################################################
#  Event Store
#######################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: eventstore
  name: eventstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventstore
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: eventstore
    spec:
      containers:
        - env:
            - name: EVENTSTORE_CLUSTER_SIZE
              value: "1"
            - name: EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP
              value: "true"
            - name: EVENTSTORE_ENABLE_EXTERNAL_TCP
              value: "true"
            - name: EVENTSTORE_EXT_HTTP_PORT
              value: "2113"
            - name: EVENTSTORE_EXT_TCP_PORT
              value: "1113"
            - name: EVENTSTORE_INSECURE
              value: "true"
            - name: EVENTSTORE_RUN_PROJECTIONS
              value: All
            - name: EVENTSTORE_START_STANDARD_PROJECTIONS
              value: "true"
          image: eventstore/eventstore:21.2.0-buster-slim
          name: eventstore
          ports:
            - containerPort: 1113
            - containerPort: 2113
          resources:
            requests:
              memory: 64Mi
              cpu: 32m
            limits:
              memory: 2048Mi
              cpu: 256m
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: eventstore
  name: eventstore
spec:
  ports:
    - name: "1113"
      port: 1113
      targetPort: 1113
    - name: "2113"
      port: 2113
      targetPort: 2113
  selector:
    app: eventstore
---
# #######################################################
# #  Jaeger
# #######################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: jaeger
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  strategy: {}
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - image: jaegertracing/all-in-one:1.48
          name: jaeger
          ports:
            - containerPort: 5775
              protocol: UDP
            - containerPort: 5778
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
            - containerPort: 9411
            - containerPort: 14268
            - containerPort: 16686
          resources:
            requests:
              memory: 64Mi
              cpu: 32m
            limits:
              memory: 2048Mi
              cpu: 256m
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: jaeger
  name: jaeger
spec:
  ports:
    - name: "5775"
      port: 5775
      protocol: UDP
      targetPort: 5775
    - name: "5778"
      port: 5778
      targetPort: 5778
    - name: "6831"
      port: 6831
      protocol: UDP
      targetPort: 6831
    - name: "6832"
      port: 6832
      protocol: UDP
      targetPort: 6832
    - name: "9411"
      port: 9411
      targetPort: 9411
    - name: "14268"
      port: 14268
      targetPort: 14268
    - name: "16686"
      port: 16686
      targetPort: 16686
  selector:
    app: jaeger
---
# #######################################################
# #  Mongo
# #######################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  strategy: {}
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - image: mongo:5
          name: mongo
          ports:
            - containerPort: 27017
          resources:
            requests:
              memory: 64Mi
              cpu: 32m
            limits:
              memory: 2048Mi
              cpu: 256m
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: mongo
  name: mongo
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    app: mongo
---
# #######################################################
# #  Postgres
# #######################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - args:
            - postgres
            - -c
            - wal_level=logical
            - -c
            - max_prepared_transactions=10  
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
          image: postgres:15.4
          name: postgres
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: 64Mi
              cpu: 32m
            limits:
              memory: 2048Mi
              cpu: 256m
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: postgres
  name: postgres
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
---
# #######################################################
# #  Rabbitmq
# #######################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - image: rabbitmq:3-management
          name: rabbitmq
          ports:
            - containerPort: 5672
            - containerPort: 15672
          resources:
            requests:
              memory: 64Mi
              cpu: 32m
            limits:
              memory: 2048Mi
              cpu: 256m
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: rabbitmq
  name: rabbitmq
spec:
  ports:
    - name: "5672"
      port: 5672
      targetPort: 5672
    - name: "15672"
      port: 15672
      targetPort: 15672
  selector:
    app: rabbitmq
---